# Generated by Django 6.0.5 on 2026-06-10 05:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TCE', 'TCE'), ('Plano de Atividades', 'Plano de Atividades'), ('Relatório', 'Relatório')], max_length=40)),
                ('hashSHA256', models.CharField(max_length=64)),
                ('valido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('ramo_atividade', models.CharField(max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUnidade', models.CharField(max_length=255)),
                ('coordenador', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('orientador', 'Orientador')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(max_length=50)),
                ('areaAtuacao', models.CharField(max_length=255)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientadores', to='app.instituicao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orientador',
                'verbose_name_plural': 'Orientadores',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_supervisionados', to='app.orientador')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumoAtividades', models.TextField()),
                ('dataReferencia', models.DateField()),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='app.aluno')),
                ('documento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_semestral', to='app.documento')),
            ],
            options={
                'verbose_name': 'Relatório Semestral',
                'verbose_name_plural': 'Relatórios Semestrais',
            },
        ),
        migrations.CreateModel(
            name='TermoDeCompromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('apoliceSeguro', models.CharField(max_length=100)),
                ('statusJuridico', models.CharField(choices=[('Pendente', 'Pendente'), ('Ativo', 'Ativo'), ('Concluído', 'Concluído')], default='Pendente', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='app.aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='app.empresa')),
            ],
            options={
                'verbose_name': 'Termo de Compromisso',
                'verbose_name_plural': 'Termos de Compromisso',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='termo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.termodecompromisso'),
        ),
    ]
