# Generated by Django 6.0.5 on 2026-06-10 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termodecompromisso',
            name='token_validacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='termodecompromisso',
            name='statusJuridico',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ativo', 'Ativo'), ('Reprovado', 'Reprovado'), ('Concluído', 'Concluído')], default='Pendente', max_length=10),
        ),
    ]
