# Generated by Django 6.0.5 on 2026-05-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('ramo_atividade', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUnidade', models.CharField(max_length=255)),
                ('coordenador', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('siape', models.CharField(max_length=50)),
                ('areaAtuacao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Orientador',
                'verbose_name_plural': 'Orientadores',
            },
        ),
        migrations.CreateModel(
            name='TermoDeCompromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('apoliceSeguro', models.CharField(max_length=100)),
                ('statusJuridico', models.CharField(choices=[('Pendente', 'Pendente'), ('Ativo', 'Ativo'), ('Concluído', 'Concluído')], default='Pendente', max_length=10)),
            ],
            options={
                'verbose_name': 'Termo de Compromisso',
                'verbose_name_plural': 'Termos de Compromisso',
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
