# Generated by Django 6.0.5 on 2026-05-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aluno_empresa_instituicao_orientador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TCE', 'TCE'), ('Plano de Atividades', 'Plano de Atividades'), ('Relatório', 'Relatório')], max_length=40)),
                ('hashSHA256', models.CharField(max_length=64)),
                ('valido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='RelatorioSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumoAtividades', models.TextField()),
                ('dataReferencia', models.DateField()),
            ],
            options={
                'verbose_name': 'Relatório Semestral',
                'verbose_name_plural': 'Relatórios Semestrais',
            },
        ),
    ]
