# Generated by Django 6.0.5 on 2026-05-28 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_documento_relatoriosemestral'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientador',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orientadores', to='app.instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termodecompromisso',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='app.aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termodecompromisso',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='app.empresa'),
            preserve_default=False,
        ),
    ]
