# Generated by Django 6.0.5 on 2026-05-29 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orientador_instituicao_termodecompromisso_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_supervisionados', to='app.orientador'),
        ),
        migrations.AddField(
            model_name='documento',
            name='termo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.termodecompromisso'),
        ),
        migrations.AddField(
            model_name='relatoriosemestral',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='app.aluno'),
        ),
        migrations.AddField(
            model_name='relatoriosemestral',
            name='documento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_semestral', to='app.documento'),
        ),
    ]
