# Generated by Django 6.0.5 on 2026-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aluno_orientador_documento_termo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
